import './globals.css';
import type { Metadata } from 'next';
import ThemeProvider from '@/theme';
import SettingsDrawer from '@/components/settings/drawer/SettingsDrawer';
import { primaryFont } from '@/theme/typography';
import MotionLazy from '@/components/animation/MotionLazy';
import { SettingsProvider } from '@/components/settings';
import { Header } from '@/components/header';
import ClientProvider from '@/contexts/client/ClientProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html className={primaryFont.className}>
      <body>
        <SettingsProvider
          defaultSettings={{
            themeMode: 'light',
            themeContrast: 'default',
            themeColorPresets: 'default',
          }}
        >
          <ThemeProvider>
            <MotionLazy>
              <SettingsDrawer />
              <ClientProvider>{children}</ClientProvider>
            </MotionLazy>
          </ThemeProvider>
        </SettingsProvider>
      </body>
    </html>
  );
};

export default RootLayout;
